version: 2

project_name: noted

before:
  hooks:
    - go mod tidy

builds:
  - binary: "noted"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin #macOS
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: "{{ .ProjectName }}_{{.Version}}_{{.Os}}_{{.Arch}}"
    files:
      - README.md
      - LICENSE
      - example.env
    wrap_in_directory: true

    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
      - goos: linux
        goarch: arm64
        format: tar.xz

dockers:
  - image_templates:
    - "mustafalo/noted-cli:{{.Version}}"
    - "mustafalo/noted-cli:latest"
  dockerfile: Dockerfile
  build_flag_templates:
    - "--build-arg CGO_ENABLED=0"
  goos: linux
  goarch:
    - amd64
    - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
