version: 2

project_name: noted

before:
  hooks:
    - go mod tidy

builds:
- binary: "noted"
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin #macOS
  goarch:
    - amd64
    - arm64

archives:
  - format: tar.gz
  # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: "{{ .ProjectName }}_{{.Version}}_{{.Os}}_{{.Arch}}"
    files:
      - README.md
      - LICENSE
      - example.env
    wrap_in_directory: true

  # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - image_templates:
      - "mustafalo/{{ .ProjectName }}:{{ .Version }}"
      - "mustafalo/{{ .ProjectName }}:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - --build-arg EXAMPLE_ENV=example.env
    skip_push: false


changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
